### ISSUE TITLE
GTK+-3.20: Applets opens in top left corner of screen

### ISSUE THREAD

**Issue by pyaazkaparatha** [mate-desktop/mate-applets#187] opened 2016-04-08 00:25 UTC
F24 Alpha GTK3 COPR repo

Clicking on clock and weather applet opens it on top left corner of screen. Sometimes happens with volume applet too. 

Tried solution: Changing themes does not help.

**Comment by raveit65** [comment] 2016-04-08 08:03
This is probably gtk+3 issue. i noticed the same with anaconda popups during installation, or in cinnamon the logout dialog is affected.
GTK+-3.20 has massive changes, no wonder that it is buggy.
You can give them a big **thank you** not to branch to gtk+-4 for those changes.
I expect that a lot of application will be buggy, ie. firefox ;)

**Comment by pyaazkaparatha** [comment] 2016-04-08 16:41
The Gnome people are giving a lot trouble. Themes never worked in past three years. Specially with fedora.

**Comment by raveit65** [comment] 2016-04-08 16:59
Well, i'm not 100% sure, maybe it is caused by latest xorg-server update.
Or X-server needs adjustments for gtk+-3.20.
But since i updated X yesterday i see that behavior with a lot of dialog windows.

**Comment by raveit65** [comment] 2016-04-08 17:03
@lukefromdc 
Do you noticed that in your debian unstable installation with latest gtk+ version?
This is the X version in fedora 24.
xorg-x11-server-Xorg-1.18.3-1.fc24.x86_64

**Comment by lukefromdc** [comment] 2016-04-08 18:03
Never ONCE had that happen in any version of MATE, with any set of patches.
I've seen this in IceWM however with it's tray. From what I've read that's as failure
of Xembed, causing a plug/socket to instead open as a separate window.

mate-panel-test-applets will show applets in separate windows at the top left, I don't
think it was meant to try to embed them into the panel. Other than that I've never seen
this happen in MATE over Ubuntu or Debian with any version of GTK3. I do have X
and Mesa from the Ubuntu PPA that offers builds from GIT master with all the
performance options enabled. Haven't tested the default Debian versions of X and
Mesa and there is no easy way to do so.

**Comment by lukefromdc** [comment] 2016-04-08 18:26
I looked at the whole issue report here, originally misunderstood it as applets themselves going to the top left, but the text of this report implies that that the applets are in the panel as intended-
but popup windows opened by them  are going to the top left corner. There were versions of GTK 3.19 during the winter that had this problem until some code in window management was changed. The code snippet below ends just under the fix I used for that in late December:

```
static void
position_calendar_popup (ClockData *cd)
{
	GtkRequisition  req;
	GtkAllocation   allocation;
	GdkScreen      *screen;
	GdkRectangle    monitor;
	GdkGravity      gravity = GDK_GRAVITY_NORTH_WEST;
	int             button_w, button_h;
	int             x, y;
	int             w, h;
	int             i, n;
	gboolean        found_monitor = FALSE;

	/* Get root origin of the toggle button, and position above that. */
	gdk_window_get_origin (gtk_widget_get_window (cd->panel_button),
			       &x, &y);

	gtk_window_get_size (GTK_WINDOW (cd->calendar_popup), &w, &h);
#if GTK_CHECK_VERSION (3, 0, 0)
	gtk_widget_get_preferred_size (cd->calendar_popup, &req, NULL);
	gtk_widget_realize (cd->calendar_popup); /*fix gtk3.20 window position */
#else
	gtk_widget_size_request (cd->calendar_popup, &req);
#endi
```f

I've got xserver-xorg-core 1.18.2-3 from Debian, which is apparently running ahead of the
Mesa PPA for X versions right now. No trouble at all here with GTK 3.20.0, 3.20.1, or 3.21.0, all built locally from git master.  Last winter those bad versions of 3.19 required expliclty calling gtk_widget_realize at the right time to get the popups to appear where they were supposed to. Finally the GNOME devs gave up on that when they realized how many places they would have to add this one line.

**Comment by raveit65** [comment] 2016-04-08 19:07
Thanks Luke, i will try that out.
But i think it's more a general problem, because i see that a lot of dialogs windows open at 0 position (x0/y0), nm-applet edit-connections dialog and cinnnamon shutdown dialog have the same problem, also with popups of anaconda (the fedora installer).
With last mentioned app i think this have to be fixed by gtk+ or xorg for fedora release, because anaconda is a release blocking application ;)

**Comment by lukefromdc** [comment] 2016-04-08 19:16
Red hat's influence over GNOME should help with this

**Comment by albertsmuktupavels** [comment] 2016-04-13 10:02
That was problem in GTK+ 3.20.2 and is fixed in 3.20.3.

https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-20&id=ba91d7d3a92d58dfe8058d31854c135353b87e01

https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-20&id=6144b2276c7298040c080f85ffa83afbe1257c54

**Comment by raveit65** [comment] 2016-04-13 10:12
Thx for the info :)

**Comment by raveit65** [comment] 2016-04-13 13:50
Fixed with http://koji.fedoraproject.org/koji/buildinfo?buildID=753965

**Closed by raveit65** 2016-04-13 13:50 UTC
