### ISSUE TITLE
many applets crash on hidpi (2560x1600 @ 2x)

### ISSUE THREAD

**Issue by tidux** [mate-desktop/mate-applets#308] opened 2018-02-15 05:58 UTC
#### Expected behaviour
Applets scale up and behave normally.

#### Actual behaviour
Applets either do not render at all, render with errors, or render so badly that parts of the display constantly flicker back and forth.  The desktop switcher does this with a 1x4 layout, but switching to 2x2 fixes that particular glitch.

#### Steps to reproduce the behaviour
Install MATE on a hidpi screen and log in.

#### MATE general version
1.20.

#### Package version
1.20.

**Comment by tidux** [comment] 2018-02-15 06:46
It seems to be Wncklet causing the problems with the tray and window switcher.  When I can actually *see* the applets in the tray, they seem to be scaled reasonably and their context menus render in hidpi.  I'm running binary packages on Arch at the moment, so it'll take a bit for me to set up a build environment.

**Comment by MingcongBai** [comment] 2018-02-23 17:27
Any updates on this issue?

**Comment by vkareh** [comment] 2018-02-23 18:27
@MingcongBai - yes, for now the solution for most distros is to build the mate-panel with the applets in-process. Fedora already switched, Ubuntu doesn't have this issue, and Gentoo/Arch are user-built. Not sure about others?

Development is still ongoing to fix it for out-of-process applets.

**Comment by MingcongBai** [comment] 2018-02-23 20:01
@vkareh Thanks for the information, but could you clarify what you meant by "build in process"?

**Comment by lukefromdc** [comment] 2018-02-23 20:05
Build with
--with-in-process-applets=wncklet,clock,fish,notification-area
or
--with-in-process-applets=all
and the applets shipped with the panel run as part of the same process as the panel. One effect of this is that Xembed is not needed, and the GtkPlug/GtkSocket method of getting the applet's window included in the panel is not used.

**Comment by MingcongBai** [comment] 2018-02-23 20:06
@vkareh Thanks for the information. However it doesn't seem like Fedora has switched, at least not in their spec.

**Comment by MingcongBai** [comment] 2018-02-23 20:06
@lukefromdc Any side-effect to be expected?

**Comment by vkareh** [comment] 2018-02-23 20:07
@MingcongBai - https://src.fedoraproject.org/rpms/mate-panel/c/7978a516a6a7f5cfdd6472006b8921b0cb487744?branch=master

The main (negative) side effect is that in-process applets, if an applet crashes it will bring down the panel along with it

**Comment by lukefromdc** [comment] 2018-02-23 20:08
With MATE 1.20, a nasty background rendering bug affecting custom backgrounds in 1.16 and 1.18 with GTK 3.22 was squashed. I've been using in-proces applets for months with no problems. Confirm that the main downside is that an applet crash takes down the whole panel. In the old days, out-of-process was considered more stable due to that, and in-process was considered lighter on resources.

**Comment by vkareh** [comment] 2018-02-23 20:12
I run them in-process as well, no negatives here so far.

To be honest @lukefromdc, I would push for changing the default build process to be in-process, but one thing still nags me: I have not seen this issue at all in Ubuntu (running 18.04 here). So what's different about Ubuntu vs other distros? what are they doing differently that the issue is not there?

**Comment by vkareh** [comment] 2018-02-23 20:17
Also, this might very well be a separate discussion, but why do we keep a handful of applets in the panel code, but then a separate repo for the others? Would it not make sense to consolidate all applets into the mate-applets repo? Applets from this repo don't seem to have this issue... also wondering what makes them different... :confused:

**Comment by lukefromdc** [comment] 2018-02-23 20:18
Is Ubuntu building applets in-process like they used to do? Look inside the debian package, if the applets are in-process you will see things like "libclock-applet" and "libfish-applet"

**Comment by vkareh** [comment] 2018-02-23 20:22
@lukefromdc - doesn't seem like that from here: https://anonscm.debian.org/git/pkg-mate/mate-panel.git/tree/debian/rules?h=ubuntu/bionic
Also, I've compiled them both ways here and still no issue. First I thought maybe the theme had something to do, but no - all themes work well... just can't reproduce on UM

**Comment by MingcongBai** [comment] 2018-02-23 20:28
Building MATE Panel with in-process applets did resolve the issue for [AOSC OS](https://github.com/AOSC-Dev/aosc-os-abbs/), thanks.

**Comment by vkareh** [comment] 2018-02-23 20:28
Is there a debian iso with 1.20, or do I still need to do that thing where you install stable and them modify all sources to dev or something like that and hope nothing else breaks? I haven't tested this on debian (but @flexiondotorg would have noticed, as he has HiDPI _and_ seems to be a bit of a Debian junkie :wink:)

**Comment by raveit65** [comment] 2018-02-24 07:37
> Thanks for the information. However it doesn't seem like Fedora has switched, at least not in their spec.

I have switched f28 to  with in-process applets, f27 still remain on 1.19.x packages before HIDPI support comes in, so it use normal build options.
I am waiting for a 1.20.1 with fixes before i update an stable release.

**Comment by vkareh** [comment] 2018-03-22 17:39
Fixed by mate-desktop/mate-panel/pull/755

**Closed by vkareh** 2018-03-22 17:39 UTC
