### ISSUE TITLE
netspeed: impossible to select device in preferences / `lo` results in crash

### ISSUE THREAD

**Issue by treysis** [mate-desktop/mate-applets#593] opened 2021-01-05 19:56 UTC
#### Expected behaviour

Selecting a network device in the combo box in `Preferences` should be remembered and still be selected if you reopen the preferences dialog. Selecting `lo` shouldn't crash (`Segmentation fault`) the applet if you reopen the `Preferences` dialog after having selected `lo`.

#### Actual behaviour

* If you select a network device in `Preferences`, close the dialog, and reopen it afterwards, the selection is reset to `Default`.
* If you select `lo` as network device in the `Preferences` dialog, close the dialog, and try to reopen `Preferences`, the applet will crash. Running the applet from cli shows `Segmentation fault`.

#### MATE general version

mate 1.24.1
mate-panel 1.25.2

#### Package version

current `master`

#### Linux Distribution

Arch Linux

**Comment by rbuj** [comment] 2021-01-05 20:41
Please, provide more information in order to determine the source of the segfault, such as #589
You can also check that it is not a duplicate of the link above.

**Comment by raveit65** [comment] 2021-01-05 20:43
I am sure
https://github.com/mate-desktop/mate-applets/pull/589
and
https://github.com/mate-desktop/mate-applets/pull/592
fix the issue.

**Comment by treysis** [comment] 2021-01-05 21:48
Partly. The crash is gone, but it doesn't remember the combo box choice if the choice is a network interface. If I select `lo` it will remember it, and only if afterwards I select `enp0s3` it will also remember this. Or if I change a checkbox.

**Comment by raveit65** [comment] 2021-01-06 09:24
I can't reproduce this issue any more.
Here the `lo`, `enp38s0`, `wlo1`, or any other virtual bridge doesn't fallback anymore to default, after https://github.com/mate-desktop/mate-applets/pull/589 https://github.com/mate-desktop/mate-applets/pull/592 and https://github.com/mate-desktop/mate-applets/pull/592, and a complete restart of the system this morning.

**Comment by treysis** [comment] 2021-01-06 15:10
No joy here, neither after restarting. Selecting `enp0s3`, the first NIC (virtual, as it's run in VirtualBox), it resets to `Default`. Chosing a 2nd virtual adapter `enp0s8` or `lo` without problems. After selecting one of the latter, also `enp0s3` is remembered.

**Comment by raveit65** [comment] 2021-01-06 16:18
Hmm, you're running Mate as a VM ?
My results are on bare metal.
What source are you use for building the applet?
Master + PRs or latest released tarball (1.25.2) + PRs?

@rbuj 
I think we should merge the open PRs which are tested, because there are more than 30 commits after 1.25.2 release.
It very easy to forgot something what is really needed for building.
Than we can see what is missing after a new release.
Keep in mind that my free spare time will limited starting with Friday this week.

**Comment by treysis** [comment] 2021-01-06 16:26
@raveit65
Yes, as VM. Don't have a machine currently where I could run it on bare metal.
mate-panel: latest released tarball (1.25.2), no additional PRs/patches/commits
mate-applets: Master + cherry-picked the 3 PRs

**Comment by rbuj** [comment] 2021-01-06 18:29
> Partly. The crash is gone, but it doesn't remember the combo box choice if the choice is a network interface instead of `lo` (e.g. `enp0s3` will revert back to `Default`). #590 doesn't fix this.

As another team member commented earlier, if the default interface is selected, the interface with the default gateway is selected. The other issues have been resolved in another thread, so this is a duplicate.

**Closed by rbuj** 2021-01-06 18:29 UTC
