### ISSUE TITLE
Stickynotes loose color after reboot

### ISSUE THREAD

**Issue by alexsl** [mate-desktop/mate-applets#105] opened 2014-10-13 13:53 UTC
Ubuntu 14.04, Mate 1.8. 
If I set background and/or text color for a note it sets correct, but after OS boot/reboot this note loose color in text area (black text on white background). Only top and bottom parts of a note colored, but not text area. 
I have posted a bug report at ubuntu-mate bugtracker: https://bugs.launchpad.net/ubuntu-mate/+bug/1380356
##

**Comment by monsta** [comment] 2015-01-30 12:06
Actually, it doesn't even survive a logout. No need to reboot to reproduce this.

**Comment by alexsl** [comment] 2015-02-01 13:56
Thanks, monsta.
As you can see note can restore color after reboot in its header and footer, but not in text editing area. Some time ago text editing control for notes was changed for another one. I think this was point when the bug was added. Something done wrong with new text editing control. Sorry, I can't find whats wrong myself - I'm not so good programmer.
If you can help, please look to this code.

**Comment by monsta** [comment] 2015-02-02 09:45
Ok, I see, it must be https://github.com/mate-desktop/mate-applets/commit/c8a85a6aa040c1d2505b957af4cfb4bd39466504 - in this commit the widget has been changed in order to add undo/redo feature to the applet (it wasn't possible with the old widget).

But I can't figure out how this change might have caused the issue...
@stefano-k: any clues? :confused:

**Comment by monsta** [comment] 2015-02-26 13:58
@stefano-k: what do you think about trying out [GtkUndoView](http://svn.jacekowski.org/chromium/trunk/third_party/undoview/?q=chromium/trunk/third_party/undoview) (it's a third-party widget) instead of GtkSourceView?

**Comment by alexsl** [comment] 2015-05-20 15:45
I don't understand why someone need "undo" functionality in this applet. Sticky notes is not a text editor, its just a short memos / reminders (about 3 - 5 words long). For example: "don't forget to do <something>" or "go to <somplace> at <sometime>" - thats all. Do you need "undo" when editing this short texts? I think you don't. May be someone just don't understand what is sticky notes applet? For long text editing we have Pluma.

**Comment by monsta** [comment] 2015-05-27 12:31
That has been added after a request in https://github.com/mate-desktop/mate-applets/issues/17.

**Comment by raveit65** [comment] 2016-03-20 12:47
@monsta 
Is this still an issue?

**Comment by monsta** [comment] 2016-03-20 13:33
Yes, in GTK+2. I think there's some issue with GTK+2 version of gtksourceview. As I suggested above, we could replace it with third-party widget, but I surely don't have time for that now (it won't be a quick job).

**Comment by alexsl** [comment] 2016-09-25 17:46
Hello. This is me again.
Ubuntu 16.04 LTS, Mate 1.12.1 :
Bug still here :(
I hope much one day someone finally fix this bug.

**Comment by monsta** [comment] 2016-12-01 10:10
Fixed in version 1.17 due to migration to GTK+3 only code.

**Closed by monsta** 2016-12-01 10:10 UTC
Labels: confirmed
