### ISSUE TITLE
Improve usuability of cpufreq applet

### ISSUE THREAD

**Issue by skoehler** [mate-desktop/mate-applets#120] opened 2015-01-06 12:22 UTC
I'm using the cpufreq applet on a quadcore system (with hyperthreading). So in my panel I have 8 icons showing the current frequency of my CPU. I have to add all 8 icons manually. Then I have to configure 7 of them so that they don't show CPU 0 but CPU 1 to 7. This is an awful process.

Instead, make the cpufreq applet more like the mate-sensors-applet (or even merge the cpufreq applet with the mate-sensors-applet). Display a list of CPUs and a checkbox next to each CPU. Let me enable/disable displaying of each CPUs frequency by clicking the checkboxes.

This way, I only need to add the applet and configure the applet once. Also, I don't 8 separate applets. which, btw, sometimes change their order for no good reason.

**Comment by infirit** [comment] 2015-01-06 12:52
duplicate of https://github.com/mate-desktop/mate-applets/issues/50

**Closed by infirit** 2015-01-06 12:52 UTC
