### ISSUE TITLE
The MATE timer applet does support transparency

### ISSUE THREAD

**Issue by physicsshark** [mate-desktop/mate-applets#136] opened 2015-05-27 16:53 UTC
I (as well as many other users) enjoy using a panel that is transparent, or partially transparent. 
 All of the other included MATE applets respect my choice of a transparent panel, except the timer applet, which has the background color from my gtk theme.

![screenshot36](https://cloud.githubusercontent.com/assets/9755486/7842067/dbeb55de-046e-11e5-9a15-2e070815b6eb.png)

**Comment by monsta** [comment] 2015-05-28 10:11
Confirmed, still present in 1.10.

**Comment by NiceandGently** [comment] 2015-06-29 09:22
With mate gtk3 version i have full transparency for ***all*** applets.
But this depends on theme settings. Menta themes support now full transparency after this commit.
https://github.com/mate-desktop/mate-themes/commit/34d3b36
Unfortunately this isn't possible with gtk2, because theming is very limited.

**Comment by infirit** [comment] 2015-08-04 10:58
should be fixed with https://github.com/mate-desktop/mate-applets/commit/cff2fddb611ed0d052df970454af1b0bfcfe01b3

**Closed by infirit** 2015-08-04 10:58 UTC
Labels: confirmed
