### ISSUE TITLE
menu buttons not clickable at screen border with TOK themes

### ISSUE THREAD

**Issue by skoehler** [mate-desktop/mate-applets#213] opened 2016-10-14 14:40 UTC
I upgraded to ubuntu 16.10 from 16.04 yesterday. I noticed one major annoyance:

I have a panel at the top of the screen and in the top left corner I have the main menu (the one which contains all the programs). If the mouse cursor is at the top of the screen, the menu buttons in the panel are not clickable. The "clickable" area has a 1 or 2 pixel border around it. Just driving the cursor against the top left corner of the screen won't allow you to click the menu anymore.

**Comment by raveit65** [comment] 2016-10-14 16:25
I can't reproduce the issue with f24 and Mate-1.16 (gtk3).
f24 and 16.10 use same gtk+-3 version.
When moving the mouse to top left corner main menu (not mate-menu from ubuntu) is clickable.
I use Blue-Submarine theme from mate-themes.

**Comment by raveit65** [comment] 2016-10-14 16:27
Same with Ambiant/Radiant-Mate themes.

**Comment by skoehler** [comment] 2016-10-14 16:29
I'll send a screenshot (I'm using TraditionalOK theme)

**Comment by skoehler** [comment] 2016-10-14 16:53
![menu](https://cloud.githubusercontent.com/assets/568090/19395728/61f7dd78-923f-11e6-8fff-3b126c422398.png)

As you can see, there's a 1 pixel border around the button

**Comment by raveit65** [comment] 2016-10-15 06:20
Thanks for reporting.
There is a 1px border around the whole screen, you can see that in a VM window.

**Comment by raveit65** [comment] 2016-10-15 06:21
Or if you use a dark desktop background.

**Comment by raveit65** [comment] 2016-10-15 07:35
Ok, the border for the whole desktop screen is fixed by
https://github.com/mate-desktop/caja/commit/dffb0850e530855fe67a4a6e8768c4b9ecf17a62
, but it does not fix the issue with TOK themes.

**Closed** 2016-10-15 09:05 UTC

**Comment by raveit65** [comment] 2016-10-15 09:08
fixed with 215d835e679cfa044797b34f38a3aa714fca9772
For the moment edit
/usr/share/caja/caja.css
/usr/share/themes/TraditionalOk/gtk-3.0/mate-applications.css
like i did in both commits.
